version: "3.8"
services:
    web:
        stdin_open: true
        container_name: rent_rooms
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
        - "3000:3000"